import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from './components/header/header';
import SearchBar from './components/search-bar/search-bar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="w-full h-full">
            <body
                className={`${inter.className} flex h-full w-full items-center flex-col`}
            >
                <Header />
                <SearchBar />
                {children}
            </body>
        </html>
    );
}
