import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import HeaderPanel from './components/header-panel/header-panel';
import SearchBarPanel from './components/search-bar-panel/search-bar-panel';
import FooterPanel from './components/footer-panel/footer-panel';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="w-full h-full">
            <body
                className={`${inter.className} flex h-full w-full items-center flex-col`}
            >
                <HeaderPanel />
                <div className="w-full h-[700px]">{children}</div>
                <FooterPanel />
            </body>
        </html>
    );
}
